server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sidefriends
    username: eraser
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
