server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sidefriends
    username: eraser
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxx
            client-secret: xxx
            scope:
            - email
            - profile
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://db-b11vh.pub-cdb.ntruss.com:3306/SF?characterEncoding=UTF-8
#    username:
#    password:
#    maximum-pool-size: 10
#    minimum-idle: 10
#
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
