server:
  port: 8080

spring:

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      redirect_url: ${OAUTH_REDIRECT_URL}
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

          kakao: # 카카오 oauth 로그인 client 설정
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao: # 카카오 oauth 로그인 provider 설정
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

image:
  server:
    base-uri: ${IMAGE_SERVER_BASE_URI}
    upload-path: /images/upload
    download-path: /images
  local:
    base-uri: ${IMAGE_LOCAL_BASE_URI}
    upload-path: /src/main/resources/images
    download-path: /images
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://db-b11vh.pub-cdb.ntruss.com:3306/SF?characterEncoding=UTF-8
#    username:
#    password:
#    maximum-pool-size: 10
#    minimum-idle: 10
#
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
